### ISSUE TITLE
Gmail not in list view

### ISSUE THREAD

**Issue by tony37** [163gal/Gmail#1]
sugar-install-bundle gmail-6.xo succeeded with no errors reported. Ubuntu 16.04 sucrose restarted. Activity not shown in list view. Activity ran successfully with sugar-launch - but no record in log activity.

**Comment by quozl** [comment]
Gmail-6 was shown in list view and worked fine on Ubuntu 16.04 when installed using Browse on Sugar 0.112, so looks like this one was fixed in Sugar.
